# Generated by Django 3.2.25 on 2025-03-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basefee',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='产品'),
        ),
        migrations.AlterUniqueTogether(
            name='zoneratedetail',
            unique_together={('product', 'surcharge', 'zone')},
        ),
        migrations.AlterUniqueTogether(
            name='zonerate',
            unique_together={('product', 'weight', 'unit', 'zone'), ('product', 'weight_band', 'zone')},
        ),
        migrations.AlterUniqueTogether(
            name='weightband',
            unique_together={('product', 'weight_band_id')},
        ),
        migrations.AddIndex(
            model_name='surcharge',
            index=models.Index(fields=['product', 'surcharge_type', 'sub_type'], name='surcharges_product_081848_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['effective_date', 'expiration_date'], name='products_effecti_4f4fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='peakseasonsurcharge',
            index=models.Index(fields=['product', 'surcharge_type'], name='peak_season_product_844624_idx'),
        ),
        migrations.AddIndex(
            model_name='basefee',
            index=models.Index(fields=['product', 'weight', 'fee_type'], name='base_fees_product_b76d53_idx'),
        ),
    ]
