# Generated by Django 3.2.25 on 2025-03-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialRule',
        ),
    ]
