# Generated by Django 3.2.25 on 2025-03-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_specialrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surcharge',
            options={'ordering': ['display_order', 'surcharge_type'], 'verbose_name': '附加费', 'verbose_name_plural': '附加费'},
        ),
        migrations.AddField(
            model_name='surcharge',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
