# Generated by Django 3.2.25 on 2025-03-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20250321_1120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zonerate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='zonerate',
            name='product',
        ),
        migrations.RemoveField(
            model_name='zonerate',
            name='weight_band',
        ),
        migrations.AlterUniqueTogether(
            name='zoneratedetail',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='zoneratedetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='zoneratedetail',
            name='surcharge',
        ),
        migrations.DeleteModel(
            name='WeightBand',
        ),
        migrations.DeleteModel(
            name='ZoneRate',
        ),
        migrations.DeleteModel(
            name='ZoneRateDetail',
        ),
    ]
