# Generated by Django 3.2.25 on 2025-03-21 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20250321_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surcharge',
            name='zone17_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone1_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone2_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone3_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone4_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone5_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone6_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone7_fee',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='zone8_fee',
        ),
        migrations.AddField(
            model_name='surcharge',
            name='charge_type',
            field=models.CharField(default='FIXED', max_length=20, verbose_name='收费类型'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='附加费代码'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='生效日期'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='失效日期'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='max_weight',
            field=models.DecimalField(decimal_places=3, default=999999, max_digits=10, verbose_name='最大重量'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='min_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='最小重量'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='附加费名称'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='百分比'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='HistoricalSurcharge',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('surcharge_id', models.IntegerField(blank=True, db_index=True, verbose_name='附加费ID')),
                ('surcharge_type', models.CharField(max_length=50, verbose_name='附加费类型')),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='子类型')),
                ('condition_desc', models.TextField(blank=True, null=True, verbose_name='条件描述')),
                ('name', models.CharField(default='', max_length=100, verbose_name='附加费名称')),
                ('code', models.CharField(default='', max_length=50, verbose_name='附加费代码')),
                ('charge_type', models.CharField(default='FIXED', max_length=20, verbose_name='收费类型')),
                ('min_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='最小重量')),
                ('max_weight', models.DecimalField(decimal_places=3, default=999999, max_digits=10, verbose_name='最大重量')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='百分比')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': 'historical 附加费',
                'verbose_name_plural': 'historical 附加费',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
