# Generated by Django 3.2.25 on 2025-03-21 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20250321_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurchargeZoneFee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=20, verbose_name='区域')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('surcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_fees', to='products.surcharge', verbose_name='附加费')),
            ],
            options={
                'verbose_name': '附加费区域费用',
                'verbose_name_plural': '附加费区域费用',
                'db_table': 'surcharge_zone_fees',
            },
        ),
        migrations.AddIndex(
            model_name='surchargezonefee',
            index=models.Index(fields=['surcharge', 'zone'], name='surcharge_z_surchar_765793_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surchargezonefee',
            unique_together={('surcharge', 'zone')},
        ),
    ]
