# Generated by Django 3.2.25 on 2025-03-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250321_1247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surchargezonefee',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='surchargezonefee',
            name='surcharge',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='charge_type',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='code',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='max_weight',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='min_weight',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='name',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='percent',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='surcharge',
            name='status',
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone10_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone10基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone10_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone10单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone11_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone11基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone11_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone11单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone12_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone12基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone12_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone12单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone13_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone13基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone13_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone13单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone14_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone14基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone14_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone14单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone15_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone15基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone15_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone15单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone16_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone16基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone16_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone16单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone18_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone18基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone18_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone18单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone19_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone19基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone19_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone19单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone20_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone20基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone20_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone20单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone9_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone9基础价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone9_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone9单位重量价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone_prices',
            field=models.JSONField(default=dict, help_text='格式: {"zone1": 10.0, "zone2": 15.0}', verbose_name='区域价格'),
        ),
        migrations.AddField(
            model_name='basefee',
            name='zone_unit_prices',
            field=models.JSONField(default=dict, help_text='格式: {"zone1": 0.5, "zone2": 0.75}', verbose_name='区域单位价格'),
        ),
        migrations.AddField(
            model_name='peakseasonsurcharge',
            name='zone_fees',
            field=models.JSONField(default=dict, help_text='格式: {"zone1": 5.0, "zone2": 7.5}', verbose_name='区域旺季附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone10_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone10附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone11_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone11附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone12_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone12附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone13_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone13附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone14_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone14附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone15_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone15附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone16_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone16附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone17_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone17附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone18_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone18附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone19_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone19附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone1_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone1附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone20_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone20附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone2_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone2附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone3_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone3附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone4_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone4附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone5_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone5附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone6_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone6附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone7_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone7附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone8_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone8附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone9_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Zone9附加费'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='zone_fees',
            field=models.JSONField(default=dict, help_text='格式: {"zone1": 5.0, "zone2": 7.5}', verbose_name='区域附加费'),
        ),
        migrations.DeleteModel(
            name='HistoricalSurcharge',
        ),
        migrations.DeleteModel(
            name='SurchargeZoneFee',
        ),
    ]
