# Generated by Django 3.2.25 on 2025-03-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_peakseasonsurcharge_zone_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefee',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='存储原始数据行，保留完整格式', null=True, verbose_name='原始数据'),
        ),
    ]
