# Generated by Django 3.2.25 on 2025-03-24 07:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_basefee_raw_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='peakseasonsurcharge',
            name='peak_season_product_844624_idx',
        ),
        migrations.AddField(
            model_name='peakseasonsurcharge',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='peakseasonsurcharge',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='peakseasonsurcharge',
            name='created_by',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='peakseasonsurcharge',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='费用金额'),
        ),
        migrations.AlterField(
            model_name='peakseasonsurcharge',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peak_season_surcharges', to='products.product'),
        ),
        migrations.AlterField(
            model_name='peakseasonsurcharge',
            name='pss_id',
            field=models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peakseasonsurcharge',
            name='surcharge_type',
            field=models.CharField(max_length=100, verbose_name='附加费类型'),
        ),
        migrations.AlterField(
            model_name='peakseasonsurcharge',
            name='updated_by',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='更新人'),
        ),
        migrations.AlterModelTable(
            name='peakseasonsurcharge',
            table=None,
        ),
    ]
