# Generated by Django 3.2.25 on 2025-03-24 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_auto_20250324_1559'),
    ]

    operations = [
        migrations.RunSQL(
            # 删除旧表
            """
            DROP TABLE IF EXISTS peak_season_surcharges;
            DROP TABLE IF EXISTS products_historicalpeakseasonsurcharge;
            """,
            # 回滚操作（如果需要）
            "SELECT 1;"
        ),
        migrations.CreateModel(
            name='PeakSeasonSurcharge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('pss_id', models.AutoField(primary_key=True, serialize=False, verbose_name='旺季附加费ID')),
                ('surcharge_type', models.CharField(max_length=50, verbose_name='附加费类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用金额')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '旺季附加费',
                'verbose_name_plural': '旺季附加费',
                'db_table': 'peak_season_surcharges',
                'indexes': [
                    models.Index(fields=['product', 'surcharge_type'], name='peak_season_product_844624_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPeakSeasonSurcharge',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('pss_id', models.IntegerField(blank=True, db_index=True, verbose_name='旺季附加费ID')),
                ('surcharge_type', models.CharField(max_length=50, verbose_name='附加费类型')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用金额')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': 'historical 旺季附加费',
                'verbose_name_plural': 'historical 旺季附加费',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
