# Generated by Django 3.2.25 on 2025-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0001_initial'),
        ('postal_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='from_city',
            field=models.ForeignKey(db_column='from_city_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='postal_codes.city', verbose_name='发件城市'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='from_country',
            field=models.ForeignKey(db_column='from_country_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_country', to='postal_codes.country', verbose_name='发件国家'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='from_postal_code',
            field=models.ForeignKey(db_column='from_postal_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_postal_code', to='postal_codes.postalcode', verbose_name='发件邮编'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='from_province',
            field=models.ForeignKey(db_column='from_province_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_province', to='postal_codes.province', verbose_name='发件省份'),
        ),
    ]
