# Generated by Django 3.2.25 on 2025-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculator', '0002_initial'),
        ('postal_codes', '0002_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='to_city',
            field=models.ForeignKey(db_column='to_city_id', on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='postal_codes.city', verbose_name='收件城市'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='to_country',
            field=models.ForeignKey(db_column='to_country_id', on_delete=django.db.models.deletion.CASCADE, related_name='to_country', to='postal_codes.country', verbose_name='收件国家'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='to_postal_code',
            field=models.ForeignKey(db_column='to_postal_id', on_delete=django.db.models.deletion.CASCADE, related_name='to_postal_code', to='postal_codes.postalcode', verbose_name='收件邮编'),
        ),
        migrations.AddField(
            model_name='freightorder',
            name='to_province',
            field=models.ForeignKey(db_column='to_province_id', on_delete=django.db.models.deletion.CASCADE, related_name='to_province', to='postal_codes.province', verbose_name='收件省份'),
        ),
    ]
