# Generated by Django 3.2.25 on 2025-03-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('calculator', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightorder',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='calculationrequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.serviceprovider', verbose_name='服务商'),
        ),
        migrations.AddField(
            model_name='calculationdetail',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='calculator.calculationrequest', verbose_name='计算请求'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='batchcalculationtask',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='batchcalculationtask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='freightorderdetail',
            index=models.Index(fields=['order', 'fee_type'], name='freight_ord_order_i_c4f410_idx'),
        ),
        migrations.AddIndex(
            model_name='freightorderdetail',
            index=models.Index(fields=['status'], name='freight_ord_status_f263e2_idx'),
        ),
        migrations.AddIndex(
            model_name='freightorder',
            index=models.Index(fields=['order_no'], name='freight_ord_order_n_ef37c9_idx'),
        ),
        migrations.AddIndex(
            model_name='freightorder',
            index=models.Index(fields=['user'], name='freight_ord_user_id_afb392_idx'),
        ),
        migrations.AddIndex(
            model_name='freightorder',
            index=models.Index(fields=['product'], name='freight_ord_product_7b97f8_idx'),
        ),
        migrations.AddIndex(
            model_name='freightorder',
            index=models.Index(fields=['status'], name='freight_ord_status_8048ca_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationrequest',
            index=models.Index(fields=['request_type', 'created_at'], name='calculation_request_c7f1a8_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationrequest',
            index=models.Index(fields=['provider', 'zone'], name='calculation_provide_d48b96_idx'),
        ),
        migrations.AddIndex(
            model_name='calculationrequest',
            index=models.Index(fields=['order_time'], name='calculation_order_t_146f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcalculationtask',
            index=models.Index(fields=['status', 'priority'], name='batch_calcu_status_370a26_idx'),
        ),
        migrations.AddIndex(
            model_name='batchcalculationtask',
            index=models.Index(fields=['expires_at'], name='batch_calcu_expires_be975f_idx'),
        ),
    ]
