# Generated by Django 3.2.25 on 2025-03-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightorder',
            name='from_city',
            field=models.CharField(max_length=100, verbose_name='发件城市'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='from_country',
            field=models.CharField(max_length=100, verbose_name='发件国家'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='from_postal_code',
            field=models.CharField(max_length=20, verbose_name='发件邮编'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='from_province',
            field=models.CharField(max_length=100, verbose_name='发件省份'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='to_city',
            field=models.CharField(max_length=100, verbose_name='收件城市'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='to_country',
            field=models.CharField(max_length=100, verbose_name='收件国家'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='to_postal_code',
            field=models.CharField(max_length=20, verbose_name='收件邮编'),
        ),
        migrations.AlterField(
            model_name='freightorder',
            name='to_province',
            field=models.CharField(max_length=100, verbose_name='收件省份'),
        ),
    ]
