# Generated by Django 3.2.25 on 2025-03-28 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_update_freightorder_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationdetail',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='calculator.calculation', verbose_name='计算结果'),
        ),
    ]
