# Generated by Django 3.2.25 on 2025-03-28 02:16

from django.db import migrations
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20250328_1003'),
    ]

    operations = [
        # 添加计算表中缺失的字段
        migrations.AddField(
            model_name='calculation',
            name='zone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='分区'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='remote_level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='偏远等级'),
        ),
        # 添加product_id外键
        migrations.AddField(
            model_name='calculation',
            name='product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name='calculations',
                to='products.product',
                verbose_name='产品'
            ),
        ),
        # 修复CalculationDetail表中calculation字段的外键关系
        migrations.RunSQL(
            sql="""
                ALTER TABLE calculation_details 
                ADD CONSTRAINT fk_calculation_details_calculation 
                FOREIGN KEY (calculation_id) 
                REFERENCES calculations(id) 
                ON DELETE CASCADE;
            """,
            reverse_sql="""
                ALTER TABLE calculation_details 
                DROP FOREIGN KEY fk_calculation_details_calculation;
            """
        ),
    ]
