# Generated by Django 3.2.25 on 2025-03-28 02:27

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_auto_20250328_1022'),
    ]

    operations = [
        # 更改calculations表的引擎为InnoDB以支持外键
        migrations.RunSQL(
            sql="ALTER TABLE calculations ENGINE=InnoDB;",
            reverse_sql="ALTER TABLE calculations ENGINE=MyISAM;"
        ),
        
        # 更改calculation_details表的引擎为InnoDB以支持外键
        migrations.RunSQL(
            sql="ALTER TABLE calculation_details ENGINE=InnoDB;",
            reverse_sql="ALTER TABLE calculation_details ENGINE=MyISAM;"
        ),
        
        # 添加外键约束
        migrations.RunSQL(
            sql="""
            ALTER TABLE calculation_details 
            ADD CONSTRAINT fk_calculation_details_calculation 
            FOREIGN KEY (calculation_id) 
            REFERENCES calculations(id) 
            ON DELETE CASCADE;
            """,
            reverse_sql="""
            ALTER TABLE calculation_details 
            DROP FOREIGN KEY fk_calculation_details_calculation;
            """
        ),
    ]
