# Generated by Django 3.2.25 on 2025-03-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20250328_1031'),
    ]

    operations = [
        # 增加fee_type字段长度
        migrations.RunSQL(
            sql="""
            ALTER TABLE calculation_details 
            MODIFY COLUMN fee_type VARCHAR(50) NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE calculation_details 
            MODIFY COLUMN fee_type VARCHAR(10) NOT NULL;
            """
        ),
    ]
