# Generated by Django 3.2.25 on 2025-04-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_auto_20250328_1034'),
    ]

    operations = [
        # 这些字段已经存在于数据库中，所以我们使用RunSQL来确保字段类型正确
        migrations.RunSQL(
            # 修改字段类型，确保与模型一致
            """
            -- 确保CalculationDetail模型与数据库表结构同步
            ALTER TABLE calculation_details MODIFY rate DECIMAL(10, 2);
            ALTER TABLE calculation_details MODIFY unit_price DECIMAL(10, 2);
            ALTER TABLE calculation_details MODIFY zone_info VARCHAR(50);
            """,
            # 向后迁移SQL（恢复原始数据类型）
            """
            ALTER TABLE calculation_details MODIFY rate DECIMAL(5, 2);
            ALTER TABLE calculation_details MODIFY zone_info JSON;
            """
        ),
    ]
