# Generated by Django 3.2.25 on 2025-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('city_id', models.AutoField(primary_key=True, serialize=False, verbose_name='城市ID')),
                ('city_code', models.CharField(max_length=10, verbose_name='城市代码')),
                ('city_name', models.CharField(max_length=100, verbose_name='城市名称')),
                ('city_name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('country_id', models.AutoField(primary_key=True, serialize=False, verbose_name='国家ID')),
                ('country_code', models.CharField(max_length=3, unique=True, verbose_name='国家代码')),
                ('country_name', models.CharField(max_length=100, verbose_name='国家名称')),
                ('country_name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('postal_id', models.AutoField(primary_key=True, serialize=False, verbose_name='邮编ID')),
                ('postal_code', models.CharField(max_length=10, verbose_name='邮编')),
                ('area_name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('area_name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '邮编',
                'verbose_name_plural': '邮编',
                'db_table': 'postal_codes',
            },
        ),
        migrations.CreateModel(
            name='PostalZoneMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('postal_code', models.CharField(max_length=10, verbose_name='邮政编码')),
                ('zone_code', models.CharField(max_length=50, verbose_name='区域代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '邮政编码区域映射',
                'verbose_name_plural': '邮政编码区域映射',
                'db_table': 'postal_zone_mapping',
                'ordering': ['postal_code', 'zone_code'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('province_id', models.AutoField(primary_key=True, serialize=False, verbose_name='省份ID')),
                ('province_code', models.CharField(max_length=10, verbose_name='省份代码')),
                ('province_name', models.CharField(max_length=100, verbose_name='省份名称')),
                ('province_name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('area_id', models.AutoField(primary_key=True, serialize=False, verbose_name='区域ID')),
                ('area_code', models.CharField(max_length=10, verbose_name='区域代码')),
                ('area_name', models.CharField(max_length=100, verbose_name='区域名称')),
                ('area_name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('area_type', models.CharField(max_length=50, verbose_name='区域类型')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '服务区域',
                'verbose_name_plural': '服务区域',
                'db_table': 'service_areas',
            },
        ),
        migrations.CreateModel(
            name='ZoneMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('mapping_id', models.AutoField(primary_key=True, serialize=False, verbose_name='映射ID')),
                ('zone', models.CharField(max_length=10, verbose_name='分区')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('postal_code', models.ForeignKey(db_column='postal_id', on_delete=django.db.models.deletion.CASCADE, to='postal_codes.postalcode', verbose_name='邮编')),
            ],
            options={
                'verbose_name': '分区映射',
                'verbose_name_plural': '分区映射',
                'db_table': 'zone_mappings',
            },
        ),
    ]
