# Generated by Django 3.2.25 on 2025-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postal_codes', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonemapping',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='zonemapping',
            name='service_area',
            field=models.ForeignKey(db_column='area_id', on_delete=django.db.models.deletion.CASCADE, to='postal_codes.servicearea', verbose_name='服务区域'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['area_code'], name='service_are_area_co_fb51e9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicearea',
            index=models.Index(fields=['status'], name='service_are_status_31bf5a_idx'),
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='postal_codes.country', verbose_name='国家'),
        ),
        migrations.AddIndex(
            model_name='postalzonemapping',
            index=models.Index(fields=['postal_code', 'status'], name='idx_postal_code_status'),
        ),
        migrations.AddIndex(
            model_name='postalzonemapping',
            index=models.Index(fields=['zone_code', 'status'], name='idx_zone_code_status'),
        ),
        migrations.AlterUniqueTogether(
            name='postalzonemapping',
            unique_together={('postal_code', 'zone_code')},
        ),
        migrations.AddField(
            model_name='postalcode',
            name='city',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='postal_codes.city', verbose_name='城市'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['country_code'], name='countries_country_f87cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['status'], name='countries_status_fa6d5d_idx'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, to='postal_codes.province', verbose_name='省份'),
        ),
        migrations.AddIndex(
            model_name='zonemapping',
            index=models.Index(fields=['product', 'postal_code', 'service_area'], name='zone_mappin_product_beecaa_idx'),
        ),
        migrations.AddIndex(
            model_name='zonemapping',
            index=models.Index(fields=['status'], name='zone_mappin_status_05e7f5_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['country', 'province_code'], name='provinces_country_53dd70_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['status'], name='provinces_status_ad6684_idx'),
        ),
        migrations.AddIndex(
            model_name='postalcode',
            index=models.Index(fields=['city', 'postal_code'], name='postal_code_city_id_f7d6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='postalcode',
            index=models.Index(fields=['status'], name='postal_code_status_7d3889_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province', 'city_code'], name='cities_provinc_c514a2_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['status'], name='cities_status_1b5a8b_idx'),
        ),
    ]
