# Generated by Django 3.2.25 on 2025-03-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteArea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField(verbose_name='服务商ID')),
                ('origin_zip', models.CharField(max_length=10, verbose_name='起始邮编')),
                ('zip_code', models.CharField(max_length=10, verbose_name='偏远地区邮编')),
                ('remote_level', models.SmallIntegerField(default=1, help_text='偏远等级：1-一级，2-二级，3-三级', verbose_name='偏远等级')),
            ],
            options={
                'verbose_name': '偏远地区',
                'verbose_name_plural': '偏远地区',
                'db_table': 'remote_areas',
            },
        ),
        migrations.CreateModel(
            name='ZipZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('zone_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='分区记录ID')),
                ('provider_id', models.IntegerField(verbose_name='服务商ID')),
                ('origin_zip', models.CharField(max_length=10, verbose_name='起始邮编')),
                ('dest_zip_start', models.CharField(max_length=10, verbose_name='目的邮编起始值')),
                ('dest_zip_end', models.CharField(max_length=10, verbose_name='目的邮编结束值')),
                ('zone_number', models.SmallIntegerField(help_text='分区号（1-8）', verbose_name='分区号')),
            ],
            options={
                'verbose_name': '邮编分区',
                'verbose_name_plural': '邮编分区',
                'db_table': 'zip_zones',
            },
        ),
        migrations.AddIndex(
            model_name='zipzone',
            index=models.Index(fields=['provider_id', 'origin_zip'], name='zip_zones_provide_972738_idx'),
        ),
        migrations.AddIndex(
            model_name='zipzone',
            index=models.Index(fields=['dest_zip_start', 'dest_zip_end'], name='zip_zones_dest_zi_8e9d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='remotearea',
            index=models.Index(fields=['provider_id', 'origin_zip'], name='remote_area_provide_34e0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='remotearea',
            index=models.Index(fields=['zip_code'], name='remote_area_zip_cod_52867a_idx'),
        ),
    ]
