# Generated by Django 3.2.25 on 2025-03-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0003_auto_20250320_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='city',
        ),
        migrations.DeleteModel(
            name='PostalZoneMapping',
        ),
        migrations.RemoveField(
            model_name='province',
            name='country',
        ),
        migrations.RemoveField(
            model_name='zonemapping',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='zonemapping',
            name='product',
        ),
        migrations.RemoveField(
            model_name='zonemapping',
            name='service_area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='PostalCode',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.DeleteModel(
            name='ServiceArea',
        ),
        migrations.DeleteModel(
            name='ZoneMapping',
        ),
    ]
