# Generated by Django 3.2.25 on 2025-03-26 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('postal_codes', '0004_remove_old_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='remotearea',
            name='remote_area_provide_34e0f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='zipzone',
            name='zip_zones_provide_972738_idx',
        ),
        migrations.RemoveField(
            model_name='remotearea',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='zipzone',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='remotearea',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider', verbose_name='服务商'),
        ),
        migrations.AddField(
            model_name='zipzone',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider', verbose_name='服务商'),
        ),
        migrations.AddIndex(
            model_name='remotearea',
            index=models.Index(fields=['provider', 'origin_zip'], name='remote_area_provide_34e0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='zipzone',
            index=models.Index(fields=['provider', 'origin_zip'], name='zip_zones_provide_972738_idx'),
        ),
    ]
