# Generated by Django 3.2.25 on 2025-03-26 01:18

from django.db import migrations


def link_providers(apps, schema_editor):
    """将provider_id字段的值转换为provider外键引用"""
    ZipZone = apps.get_model('postal_codes', 'ZipZone')
    RemoteArea = apps.get_model('postal_codes', 'RemoteArea')
    ServiceProvider = apps.get_model('core', 'ServiceProvider')
    
    # 建立id到服务商对象的映射
    provider_map = {provider.id: provider for provider in ServiceProvider.objects.filter(is_deleted=False)}
    
    # 更新ZipZone表
    for zip_zone in ZipZone.objects.all():
        if zip_zone.provider_id in provider_map:
            zip_zone.provider = provider_map[zip_zone.provider_id]
            zip_zone.save(update_fields=['provider'])
    
    # 更新RemoteArea表
    for remote_area in RemoteArea.objects.all():
        if remote_area.provider_id in provider_map:
            remote_area.provider = provider_map[remote_area.provider_id]
            remote_area.save(update_fields=['provider'])


def reverse_link_providers(apps, schema_editor):
    """数据回滚操作（可选）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0005_auto_20250326_0917'),
    ]

    operations = [
        migrations.RunPython(link_providers, reverse_link_providers),
    ]
