# Generated by Django 3.2.25 on 2025-03-26 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0007_auto_20250326_0941'),
    ]

    operations = [
        # 使用RunSQL删除zone_id字段
        migrations.RunSQL(
            # 执行SQL
            """
            -- 删除zone_id字段的唯一索引和字段本身
            ALTER TABLE zip_zones DROP INDEX zone_id;
            ALTER TABLE zip_zones DROP COLUMN zone_id;
            """,
            # 回滚SQL（如果需要恢复，这里留空表示不支持回滚）
            None
        ),
    ]
