# Generated by Django 3.2.25 on 2025-03-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0008_auto_20250326_0951'),
    ]

    operations = [
        migrations.RunSQL(
            # 执行SQL - 修改remote_level字段类型
            """
            -- 创建新的临时表，保留原表结构但改变remote_level类型
            CREATE TABLE remote_areas_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                provider_id INTEGER REFERENCES core_serviceprovider(id),
                origin_zip VARCHAR(10),
                zip_code VARCHAR(10),
                remote_level VARCHAR(50) DEFAULT '一级偏远',
                created_at DATETIME,
                updated_at DATETIME,
                created_by VARCHAR(100),
                updated_by VARCHAR(100),
                is_deleted BOOLEAN DEFAULT 0,
                UNIQUE(provider_id, origin_zip, zip_code)
            );
            
            -- 将数据从旧表复制到新表，同时转换remote_level的值
            INSERT INTO remote_areas_new(id, provider_id, origin_zip, zip_code, remote_level, 
                created_at, updated_at, created_by, updated_by, is_deleted)
            SELECT id, provider_id, origin_zip, zip_code,
                CASE 
                    WHEN remote_level = 1 THEN '一级偏远'
                    WHEN remote_level = 2 THEN '二级偏远'
                    WHEN remote_level = 3 THEN '三级偏远'
                    ELSE '特殊偏远'
                END,
                created_at, updated_at, created_by, updated_by, is_deleted
            FROM remote_areas;
                
            -- 删除旧表
            DROP TABLE remote_areas;
            
            -- 重命名新表为原表名
            ALTER TABLE remote_areas_new RENAME TO remote_areas;
            """,
            # 回滚SQL
            """
            -- 创建新的临时表，保留原表结构但改变remote_level类型
            CREATE TABLE remote_areas_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                provider_id INTEGER REFERENCES core_serviceprovider(id),
                origin_zip VARCHAR(10),
                zip_code VARCHAR(10),
                remote_level SMALLINT DEFAULT 1,
                created_at DATETIME,
                updated_at DATETIME,
                created_by VARCHAR(100),
                updated_by VARCHAR(100),
                is_deleted BOOLEAN DEFAULT 0,
                UNIQUE(provider_id, origin_zip, zip_code)
            );
            
            -- 将数据从旧表复制到新表，同时转换remote_level的值
            INSERT INTO remote_areas_new(id, provider_id, origin_zip, zip_code, remote_level, 
                created_at, updated_at, created_by, updated_by, is_deleted)
            SELECT id, provider_id, origin_zip, zip_code,
                CASE 
                    WHEN remote_level = '一级偏远' THEN 1
                    WHEN remote_level = '二级偏远' THEN 2
                    WHEN remote_level = '三级偏远' THEN 3
                    ELSE 1
                END,
                created_at, updated_at, created_by, updated_by, is_deleted
            FROM remote_areas;
                
            -- 删除旧表
            DROP TABLE remote_areas;
            
            -- 重命名新表为原表名
            ALTER TABLE remote_areas_new RENAME TO remote_areas;
            """
        ),
    ]
