# Generated by Django 3.2.25 on 2025-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0009_update_remote_level_type'),
    ]

    operations = [
        migrations.RunSQL(
            # 向前迁移SQL
            """
            -- 修改 zip_zones 表，添加 BaseModel 所需的字段
            ALTER TABLE zip_zones ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            ALTER TABLE zip_zones ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            ALTER TABLE zip_zones ADD COLUMN created_by VARCHAR(100) NULL;
            ALTER TABLE zip_zones ADD COLUMN updated_by VARCHAR(100) NULL;
            ALTER TABLE zip_zones ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
            """,
            # 向后迁移SQL
            """
            -- 如需回滚，移除添加的字段
            ALTER TABLE zip_zones DROP COLUMN created_at;
            ALTER TABLE zip_zones DROP COLUMN updated_at;
            ALTER TABLE zip_zones DROP COLUMN created_by;
            ALTER TABLE zip_zones DROP COLUMN updated_by;
            ALTER TABLE zip_zones DROP COLUMN is_deleted;
            """
        ),
        migrations.RunSQL(
            # 向前迁移SQL
            """
            -- 修改 remote_areas 表，添加 BaseModel 所需的字段
            ALTER TABLE remote_areas ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            ALTER TABLE remote_areas ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
            ALTER TABLE remote_areas ADD COLUMN created_by VARCHAR(100) NULL;
            ALTER TABLE remote_areas ADD COLUMN updated_by VARCHAR(100) NULL;
            ALTER TABLE remote_areas ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE;
            """,
            # 向后迁移SQL
            """
            -- 如需回滚，移除添加的字段
            ALTER TABLE remote_areas DROP COLUMN created_at;
            ALTER TABLE remote_areas DROP COLUMN updated_at;
            ALTER TABLE remote_areas DROP COLUMN created_by;
            ALTER TABLE remote_areas DROP COLUMN updated_by;
            ALTER TABLE remote_areas DROP COLUMN is_deleted;
            """
        ),
    ]
