# Generated by Django 3.2.25 on 2025-03-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0010_auto_20250328_1038'),
    ]

    operations = [
        # 使用ALTER TABLE CHANGE COLUMN来确保列已存在的情况
        migrations.RunSQL(
            # 向前迁移SQL - 尝试修改已存在的字段，如果不存在则忽略错误
            """
            -- 确保远程地区表中的remote_level是VARCHAR类型而不是INT
            ALTER TABLE remote_areas MODIFY COLUMN remote_level VARCHAR(50) DEFAULT '1';
            
            -- 确保表引擎为InnoDB以支持外键
            ALTER TABLE zip_zones ENGINE=InnoDB;
            ALTER TABLE remote_areas ENGINE=InnoDB;
            """,
            # 向后迁移SQL - 无需操作
            "SELECT 1;"
        ),
    ]
