# Generated by Django 3.2.25 on 2025-04-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postal_codes', '0011_fix_model_structure'),
    ]

    operations = [
        migrations.RunSQL(
            # 向前迁移SQL - 确保模型和数据库结构同步
            """
            -- 确保ZipZone模型与数据库表结构同步
            ALTER TABLE zip_zones MODIFY zone_number INT;
            """,
            # 向后迁移SQL
            """
            ALTER TABLE zip_zones MODIFY zone_number SMALLINT(6);
            """
        ),
    ]
