# Generated by Django 3.2.25 on 2025-03-19 14:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('rate_id', models.AutoField(primary_key=True, serialize=False, verbose_name='费率ID')),
                ('rate_type', models.CharField(max_length=50, verbose_name='费率类型')),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='费率值')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('expiration_date', models.DateField(verbose_name='失效日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '燃油费率',
                'verbose_name_plural': '燃油费率',
                'db_table': 'fuel_rates',
            },
        ),
        migrations.CreateModel(
            name='FuelRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('old_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='原费率')),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='新费率')),
                ('change_type', models.CharField(choices=[('MANUAL', '手动修改'), ('SYSTEM', '系统调整')], max_length=10, verbose_name='变更类型')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='变更原因')),
                ('fuel_rate', models.ForeignKey(db_column='fuel_rate_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='fuel_rates.fuelrate', verbose_name='燃油费率')),
            ],
            options={
                'verbose_name': '费率历史',
                'verbose_name_plural': '费率历史',
                'db_table': 'fuel_rate_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
