# Generated by Django 3.2.25 on 2025-03-19 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel_rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelratehistory',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='fuelrate',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='产品'),
        ),
        migrations.AddIndex(
            model_name='fuelrate',
            index=models.Index(fields=['product', 'rate_type'], name='fuel_rates_product_323b29_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelrate',
            index=models.Index(fields=['effective_date', 'expiration_date'], name='fuel_rates_effecti_deca27_idx'),
        ),
        migrations.AddIndex(
            model_name='fuelrate',
            index=models.Index(fields=['status'], name='fuel_rates_status_0776c0_idx'),
        ),
    ]
