# Generated by Django 3.2.25 on 2025-03-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_rates', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fuelrate',
            name='fuel_rates_product_323b29_idx',
        ),
        migrations.RemoveField(
            model_name='fuelrate',
            name='rate_type',
        ),
        migrations.AddIndex(
            model_name='fuelrate',
            index=models.Index(fields=['product'], name='fuel_rates_product_104f09_idx'),
        ),
    ]
