# Generated by Django 3.2.25 on 2025-03-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('fuel_rates', '0003_auto_20250325_1641'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelrate',
            index=models.Index(fields=['provider'], name='fuel_rates_provide_579e01_idx'),
        ),
    ]
