# Generated by Django 3.2.25 on 2025-04-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_rates', '0006_auto_20250325_1655'),
    ]

    operations = [
    ]
