import type { ThemeToken } from './types';

export interface ThemePreset {
  id: string;
  name: string;
  description?: string;
  token: ThemeToken;
}

export const lightPresets: ThemePreset[] = [
  {
    id: 'default',
    name: '默认',
    description: '默认主题',
    token: {
      colorPrimary: '#409eff',
      colorSuccess: '#67c23a',
      colorWarning: '#e6a23c',
      colorError: '#f56c6c',
      colorInfo: '#909399',
      colorTextPrimary: '#303133',
      colorTextRegular: '#606266',
      colorTextSecondary: '#909399',
      colorBorder: '#DCDFE6',
      colorBorderLight: '#E4E7ED',
      colorBackground: '#ffffff',
      colorBackgroundPage: '#f2f3f5',
      spacingMini: '4px',
      spacingSmall: '8px',
      spacingBase: '16px',
      spacingLarge: '24px',
      spacingXl: '32px',
      borderRadiusSmall: '2px',
      borderRadiusBase: '4px',
      borderRadiusLarge: '8px',
      boxShadow: '0 2px 12px 0 rgba(0, 0, 0, 0.1)',
      boxShadowLight: '0 2px 4px 0 rgba(0, 0, 0, 0.1)',
      boxShadowDark: '0 2px 16px 0 rgba(0, 0, 0, 0.1)',
      boxShadowHover: '0 4px 16px 0 rgba(0, 0, 0, 0.1)',
      breakpointSm: '576px',
      breakpointMd: '768px',
      breakpointLg: '992px',
      breakpointXl: '1200px',
      headerHeight: '64px',
      sidebarWidth: '256px',
      sidebarCollapsedWidth: '80px',
      toolbarHeight: '48px',
      tabbarHeight: '40px',
      footerHeight: '48px',
      cardPadding: '24px',
      tablePadding: '16px',
      formLabelWidth: '120px',
      formItemMargin: '24px',
      inputHeight: '32px',
      buttonHeight: '32px',
      buttonPadding: '16px',
    },
  },
  {
    id: 'modern',
    name: '现代',
    description: '现代风格主题',
    token: {
      colorPrimary: '#722ed1',
      colorSuccess: '#13c2c2',
      colorWarning: '#fa8c16',
      colorError: '#eb2f96',
      colorInfo: '#8c8c8c',
      colorTextPrimary: '#262626',
      colorTextRegular: '#595959',
      colorTextSecondary: '#8c8c8c',
      colorBorder: '#d9d9d9',
      colorBorderLight: '#f0f0f0',
      colorBackground: '#ffffff',
      colorBackgroundPage: '#f5f5f5',
      spacingMini: '4px',
      spacingSmall: '8px',
      spacingBase: '16px',
      spacingLarge: '24px',
      spacingXl: '32px',
      borderRadiusSmall: '4px',
      borderRadiusBase: '8px',
      borderRadiusLarge: '16px',
      boxShadow: '0 4px 16px 0 rgba(0, 0, 0, 0.1)',
      boxShadowLight: '0 2px 8px 0 rgba(0, 0, 0, 0.1)',
      boxShadowDark: '0 8px 24px 0 rgba(0, 0, 0, 0.1)',
      boxShadowHover: '0 8px 24px 0 rgba(0, 0, 0, 0.15)',
      breakpointSm: '576px',
      breakpointMd: '768px',
      breakpointLg: '992px',
      breakpointXl: '1200px',
      headerHeight: '72px',
      sidebarWidth: '280px',
      sidebarCollapsedWidth: '88px',
      toolbarHeight: '56px',
      tabbarHeight: '48px',
      footerHeight: '56px',
      cardPadding: '32px',
      tablePadding: '24px',
      formLabelWidth: '140px',
      formItemMargin: '32px',
      inputHeight: '40px',
      buttonHeight: '40px',
      buttonPadding: '24px',
    },
  },
];

export const darkPresets: ThemePreset[] = [
  {
    id: 'dark-default',
    name: '深色默认',
    description: '默认深色主题',
    token: {
      colorPrimary: '#409eff',
      colorSuccess: '#67c23a',
      colorWarning: '#e6a23c',
      colorError: '#f56c6c',
      colorInfo: '#909399',
      colorTextPrimary: '#E5EAF3',
      colorTextRegular: '#CFD3DC',
      colorTextSecondary: '#A3A6AD',
      colorBorder: '#4C4D4F',
      colorBorderLight: '#363637',
      colorBackground: '#141414',
      colorBackgroundPage: '#1e1e1e',
      spacingMini: '4px',
      spacingSmall: '8px',
      spacingBase: '16px',
      spacingLarge: '24px',
      spacingXl: '32px',
      borderRadiusSmall: '2px',
      borderRadiusBase: '4px',
      borderRadiusLarge: '8px',
      boxShadow: '0 2px 12px 0 rgba(0, 0, 0, 0.3)',
      boxShadowLight: '0 2px 4px 0 rgba(0, 0, 0, 0.3)',
      boxShadowDark: '0 2px 16px 0 rgba(0, 0, 0, 0.3)',
      boxShadowHover: '0 4px 16px 0 rgba(0, 0, 0, 0.3)',
      breakpointSm: '576px',
      breakpointMd: '768px',
      breakpointLg: '992px',
      breakpointXl: '1200px',
      headerHeight: '64px',
      sidebarWidth: '256px',
      sidebarCollapsedWidth: '80px',
      toolbarHeight: '48px',
      tabbarHeight: '40px',
      footerHeight: '48px',
      cardPadding: '24px',
      tablePadding: '16px',
      formLabelWidth: '120px',
      formItemMargin: '24px',
      inputHeight: '32px',
      buttonHeight: '32px',
      buttonPadding: '16px',
    },
  },
];

export function getThemePreset(id: string): ThemePreset | undefined {
  return [...lightPresets, ...darkPresets].find(preset => preset.id === id);
}

export function getDefaultPreset(isDark: boolean): ThemePreset {
  return isDark ? darkPresets[0] : lightPresets[0];
}

export function getPresets(isDark: boolean): ThemePreset[] {
  return isDark ? darkPresets : lightPresets;
}
